services:
  mysql-db:
    image: mysql:8.0
    container_name: objectives_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Adm1n@Cr0n1Ras3nNa"
      MYSQL_DATABASE: "objectives_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "Adm1n@Cr0n1Ras3nNa"
    ports:
      - "3309:3306" # <-- Usaremos el 3309 para saltarnos cualquier bloqueo del 3306/3308
    volumes:
      - ./Database/data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: gestor_db
    restart: always
    ports:
      - "8081:8080"