# 1. Configuración del Servidor
server.port=8088

# 2. Configuración de la Base de Datos (Docker MySQL)
# Asegúrate de que 'mental_health_db' sea el nombre que pusiste en tu docker-compose
spring.datasource.url=jdbc:mysql://localhost:3309/objectives_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=Adm1n@Cr0n1Ras3nNa
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Configuración de JPA / Hibernate
# 'update' es mejor ahora que ya tienes datos, así no borras todo cada vez que reinicias
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect